---
version: "3"
services:
  nautobot:
    build:
      context: "../"
      dockerfile: "development/Dockerfile"
    image: "nautobot-netbox-importer/nautobot:py${PYTHON_VER}"
    command: >
      sh -c "nautobot-server migrate &&
             nautobot-server runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - "postgres"
      - "redis"
    env_file:
      - "./dev.env"
    volumes:
      - "../:/source"
    tty: true
  worker:
    build:
      context: "../"
      dockerfile: "development/Dockerfile"
    image: "nautobot-netbox-importer/nautobot:py${PYTHON_VER}"
    command: "sh -c 'nautobot-server rqworker'"
    depends_on:
      - "nautobot"
    env_file:
      - "./dev.env"
    volumes:
      - "../:/source"
    tty: true
  postgres:
    image: "postgres:13"
    env_file: "dev.env"
    volumes:
      - "pgdata_nautobot_netbox_importer:/var/lib/postgresql/data"
  redis:
    image: "redis:6-alpine"
    command:
      - "sh"
      - "-c"  # this is to evaluate the $REDIS_PASSWORD from the env
      - "redis-server --appendonly yes --requirepass $$REDIS_PASSWORD"  ## $$ because of docker-compose
    env_file: "./dev.env"
volumes:
  pgdata_nautobot_netbox_importer:  # yamllint disable-line rule:empty-values
